import "./globals.css";
import pachetto from "../../package.json";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <p>v{pachetto.version}</p>
      </body>
    </html>
  );
}
